FROM python

# Set the working directory
WORKDIR /app

# Install dependencies
#COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files
COPY .devcontainer .

# CMD ["python", "app.py"]  # Replace with your app's entry point